#!/bin/bash

branchName=$1
oldVersion=$2
newVersion=$3
newMajorMinor=$4
platform=$5
repository=$6


echo $

if [[ "$branchName" =~ "renovate/angular"* ]]; then
  echo "Branch: $branchName; Old version: $oldVersion; New MajorMinorVersion: $newMajorMinor"
fi
