#!/bin/bash

branchName=$1
oldVersion=$2
newVersion=$3
newMajorMinor=$4
platform=$5
repository=$6

if [[ "$branchName" =~ "renovate/angular"* ]]; then
  echo "Branch: $branchName; Old version: $oldVersion; New MajorMinorVersion: $newMajorMinor"
  currentVersion=$oldVersion
  npm install
  while [ $currentVersion -lt $newVersion ] ; do
    currentVersion=`expr $currentVersion + 1`
    ng update @angular/core@$currentVersion @angular/cli@$currentVersion --allow-dirty
  done
fi
