#!/bin/bash
set -x

branchName=$1
currentVersion=$2
newVersion=$3
newMajorMinor=$4
platform=$5
repository=$6


echo $

if [[ "$branchName" =~ renovate/.*quarkus.platform.version ]]; then
  echo "Branch: $branchName; Old version: $oldVersion; New MajorMinorVersion: $newMajorMinor"
  mvn versions:set-property -Dproperty=quarkus.platform.version -DnewVersion=$currentVersion
  cat pom.xml
  /tmp/renovate/repos/$platform/$repository/mvnw -f /tmp/renovate/repos/$platform/$repository/pom.xml io.quarkus.platform:quarkus-maven-plugin:$newVersion:update
  cat pom.xml
fi
