#!/bin/bash

branchName=$1
oldVersion=$2
newVersion=$3
newMajorMinor=$4
platform=$5
repository=$6


echo $

if [ "$branchName" = "renovate/major-quarkus.platform.version" ]; then
  echo "Branch: $branchName; Old version: $oldVersion; New MajorMinorVersion: $newMajorMinor"
  /tmp/renovate/repos/$platform/$repository/mvnw -f /tmp/renovate/repos/$platform/$repository/pom.xml quarkus:update -Dquarkus.platform.version=$oldVersion -Dstream=$newMajorMinor
fi
