@startuml
box A new Hope - failure
participant Developer

participant Renovate

Renovate -> OpenRewrite : recognizes new version and executes OpenRewrite
activate Renovate
activate OpenRewrite

OpenRewrite --> Renovate : makes code changes
deactivate OpenRewrite

Renovate -> "Git Repository" : pushes code changes and creates Pull Request
deactivate Renovate
activate "Git Repository"

"Git Repository" -> "Build-Pipeline" : git push triggers Build-Pipeline
activate "Build-Pipeline"
"Build-Pipeline" --> "Build-Pipeline" : fails
"Build-Pipeline" -> "Git Repository" : creates comment in Pull Request with DevSpace-URL
deactivate "Build-Pipeline"

"Git Repository" --> Developer : gets notified
activate Developer
Developer -> DevSpace : creates and opens DevSpace
deactivate Developer
activate DevSpace

DevSpace -> "Git Repository" : fixes and pushes code changes

"Git Repository" -> "Build-Pipeline" : git push triggers Build-Pipeline
activate "Build-Pipeline"
"Build-Pipeline" --> "Build-Pipeline" : successful
"Build-Pipeline" --> "Git Repository" :
deactivate "Build-Pipeline"

"Git Repository" -> Developer : notifies
activate Developer

Developer -> DevSpace : deletes DevSpace
deactivate DevSpace



Developer -> "Git Repository" : merges Pull Request
deactivate Developer

deactivate "Git Repository"

end box
@enduml