name: hello-world

on:
  workflow_dispatch:
    inputs:
        msg:
          description: 'Message'
          required: true 

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello ${{ github.event.inputs.msg }}!"